In [10]:
import numpy as np

In [11]:
# Numpy Basics
array = np.array([1,2,3])
print(array)

[1 2 3]


In [12]:
#2-d array
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
#get dimensions
array.ndim


1

In [14]:
b.shape

(2, 3)

In [15]:
array.dtype

dtype('int64')

In [16]:
b.itemsize

8

In [17]:
b.size

6

In [18]:
b.nbytes

48