In [2]:
import numpy as np

In [3]:
# Numpy Basics
array = np.array([1,2,3])
print(array)

[1 2 3]


In [4]:
#2-d array
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
#get dimensions
array.ndim


1

In [7]:
b.shape

(2, 3)

In [10]:
array.dtype

dtype('int32')

In [11]:
b.itemsize

8

In [12]:
b.size

6

In [13]:
b.nbytes

48